# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true # Removed in Keyll 3

# Setup
title:            Python Monty
tagline:          'A Jekyll theme'
description:      'Explaining the terrible code I write as I go. Mostly in Python'
url:              http://z3ugma.github.io
baseurl:          /

author:
  name:           'Fred Turkington'
  url:            http://z3ugma.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/z3ugma/z3ugma.github.io
