---
title: Python Monty
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: kramdown
highlighter: rouge
permalink: pretty
gems:
- jekyll-paginate
tagline: Terrible code, restaurant reviews, and recipes
description: Explaining the terrible code I write as I go. Mostly in Python. Also
  some restaurant reviews and recipes.
url: http://z3ugma.github.io
baseurl: "/"
author:
  name: Fred Turkington
  url: http://z3ugma.github.io
paginate: 5
version: 2.1.0
github:
  repo: https://github.com/z3ugma/z3ugma.github.io
