# Dependencies
markdown:         kramdown
highlighter:      rouge
permalink:        pretty
plugins:             [jekyll-paginate]
title:            Python Monty
tagline:          'Leave it better than you found it.'
description:      'Leave it better than you found it.'
url:              'http://z3ugma.github.io'
baseurl:          ''
author:
  name:           'Fred Turkington'
  url:            'http://z3ugma.github.io'
paginate:         5
