# Dependencies
markdown:         kramdown
highlighter:      rouge
permalink:        pretty
plugins:             [jekyll-paginate]
title:            Python Monty
tagline:          'Terrible code, restaurant reviews, and recipes'
description:      'Explaining the terrible code I write as I go. Mostly in Python. Also some restaurant reviews and recipes.'
url:              'http://z3ugma.github.io'
baseurl:          ''
author:
  name:           'Fred Turkington'
  url:            'http://z3ugma.github.io'
paginate:         5
